2018-04-24 14:33:33,050 39728-123145414512640 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:34:03,147 39728-123145414512640 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:34:03,457 39728-123145414512640 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:34:33,565 39728-123145414512640 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:34:34,328 39728-123145414512640 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:35:04,414 39728-123145414512640 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:35:04,722 39728-123145414512640 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:35:34,806 39728-123145414512640 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:35:35,268 39728-123145414512640 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:36:49,277 39752-123145338384384 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:36:49,912 39752-123145338384384 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message='Save the post successfully.')
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:37:20,029 39752-123145338384384 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:37:20,625 39752-123145338384384 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message='Save the post successfully.')
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:38:10,172 39763-123145575444480 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:38:10,803 39763-123145575444480 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:38:40,902 39763-123145575444480 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:38:41,165 39763-123145575444480 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:39:11,288 39763-123145575444480 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:39:11,832 39763-123145575444480 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:39:41,931 39763-123145575444480 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:39:42,222 39763-123145575444480 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:40:12,311 39763-123145575444480 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:40:12,757 39763-123145575444480 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:40:42,872 39763-123145575444480 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:40:43,378 39763-123145575444480 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:41:13,453 39763-123145575444480 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:41:13,761 39763-123145575444480 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 218, in kline_huobi
    return jsonify(success=True, message=_('Save the post successfully.'))
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/lgp/Desktop/python-workspace/venv/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
2018-04-24 14:41:38,519 39777-123145551794176 INFO: Found 385 prices [in /Users/lgp/Desktop/python-workspace/demo/app/views/public.py:158]
2018-04-24 14:42:00,980 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:42:31,716 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:43:02,425 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:43:33,244 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:44:03,608 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:44:34,267 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:45:04,894 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:45:35,629 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:46:06,308 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:46:36,918 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:47:07,696 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:47:38,700 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:48:09,060 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:48:39,635 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:49:10,188 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:49:40,599 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:50:11,275 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:50:41,980 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:51:12,739 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:51:43,100 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:52:13,698 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:52:44,038 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:53:14,942 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:53:45,738 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:54:16,141 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:54:46,563 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:55:17,264 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:55:47,822 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:56:18,352 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:56:48,812 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:57:19,603 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:57:49,983 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:58:20,637 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:58:51,242 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:59:21,873 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 14:59:52,267 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:00:23,001 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:00:53,635 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:01:24,016 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:01:31,666 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 15:01:54,732 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:02:25,122 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:02:55,797 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:03:26,524 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:03:56,951 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:04:01,955 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 15:04:32,132 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:05:02,777 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:05:33,139 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:06:03,797 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:06:34,529 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:07:04,870 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:07:35,517 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:08:06,234 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:08:36,834 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:09:07,367 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:09:37,899 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:10:08,497 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:10:39,240 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:11:09,962 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:11:40,658 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:12:11,294 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:12:41,913 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:13:12,525 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:13:43,127 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:14:13,757 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:14:44,488 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:15:14,870 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:15:45,503 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:16:15,835 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:16:46,384 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:17:16,740 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:17:47,466 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:18:18,120 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:18:48,865 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:19:19,331 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:19:50,002 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:20:20,461 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:20:51,260 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:21:22,013 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:21:31,676 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 15:21:52,791 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:22:23,520 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:22:53,943 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:23:24,439 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:37:48,996 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:37:54,151 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 15:38:24,469 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:38:55,105 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:39:25,699 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:39:56,086 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:40:26,471 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:40:56,907 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:41:27,563 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:41:32,100 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 15:41:58,202 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:42:29,107 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:42:59,814 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:43:30,284 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:44:00,966 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:44:34,340 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:45:05,150 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:45:35,856 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:46:06,726 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:46:37,175 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:47:07,952 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:47:38,418 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 15:48:09,173 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:17:45,013 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:17:50,153 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 16:17:50,241 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 16:18:20,488 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:18:51,232 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:19:21,930 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:20:32,005 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:20:37,019 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 16:21:07,966 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:21:38,578 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:22:08,987 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:22:39,536 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:23:10,585 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:23:40,965 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:24:11,359 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:24:41,686 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:25:12,382 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:25:42,897 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:26:13,565 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:26:45,021 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:27:15,764 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:27:46,609 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:28:17,902 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:28:48,824 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:29:19,647 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:29:50,078 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:30:20,533 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:30:51,182 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:31:21,652 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:35:39,016 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:35:44,030 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 16:36:14,408 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:36:45,006 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:37:15,622 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:37:46,231 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:37:50,679 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 16:38:16,763 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:38:47,474 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:39:18,110 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:39:48,717 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:40:19,350 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:40:49,731 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:41:20,539 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:41:51,287 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:42:22,041 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:42:52,426 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:43:23,146 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:43:53,733 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 16:44:24,362 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 17:21:37,022 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 17:21:42,173 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 17:21:42,182 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 20:05:59,020 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 20:06:01,694 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 20:06:01,701 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 20:06:31,881 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 20:21:46,018 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 20:21:51,030 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 22:09:58,465 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 22:10:03,917 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 22:10:03,949 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 23:02:31,332 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:02:36,475 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 23:02:36,507 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 23:03:06,838 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:11:09,345 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 23:11:40,444 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:27:05,332 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:27:10,356 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 23:27:10,361 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 23:27:40,527 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:31:09,111 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:31:14,452 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 23:31:44,993 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:41:40,504 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:51:08,318 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-24 23:51:13,351 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-24 23:51:13,675 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-24 23:51:44,400 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:08:05,909 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:11:10,347 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:11:15,384 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 00:11:16,393 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 00:11:46,090 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:21:08,298 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:21:13,338 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 00:21:44,246 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:31:09,398 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:31:14,462 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 00:31:16,481 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 00:31:44,999 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:46:08,290 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:46:13,357 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 00:46:43,422 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:52:08,286 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 00:52:13,311 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 00:52:13,343 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 00:52:43,489 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:01:08,286 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:01:13,322 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 01:01:43,742 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:13:07,301 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:13:12,329 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 01:13:12,341 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 01:13:43,219 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:25:08,274 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:25:13,326 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 01:25:44,886 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:31:38,417 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:41:07,290 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:41:12,330 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 01:41:12,339 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 01:41:42,659 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:55:07,285 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 01:55:12,321 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 01:55:42,714 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:04:07,301 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:04:12,337 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 02:04:12,546 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 02:04:43,545 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:11:38,127 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:26:07,280 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:26:12,319 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 02:26:12,325 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 02:26:42,368 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:31:06,347 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:31:11,405 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 02:31:41,652 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:47:03,297 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 02:47:08,350 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 02:47:08,386 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 02:47:39,269 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:01:06,279 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:01:11,311 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 03:01:42,285 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:11:07,340 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:11:12,364 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 03:11:12,374 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 03:11:42,546 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:27:03,310 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:27:08,476 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 03:27:39,600 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:35:08,618 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 03:35:38,227 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:41:06,304 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:41:11,340 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 03:41:41,625 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:51:06,270 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 03:51:11,353 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 03:51:41,643 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 04:05:06,311 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 04:05:11,520 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 04:05:11,529 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 04:05:42,383 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 04:15:36,481 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 04:31:32,323 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 04:31:37,353 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 04:31:37,572 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 04:32:07,717 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 04:45:54,329 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 04:45:59,482 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 09:07:26,822 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 09:07:56,481 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:08:27,281 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:08:58,108 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:09:28,645 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:09:59,777 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:10:31,109 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:11:01,856 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:11:32,525 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:12:02,955 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:12:33,875 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:13:04,696 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:13:09,704 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 09:13:39,886 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:14:10,618 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:14:41,663 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:15:12,370 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:15:43,425 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:16:14,439 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:16:45,080 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:17:15,824 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:17:46,807 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:18:17,546 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:18:48,037 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:19:18,880 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:19:49,578 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:20:20,508 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:20:50,881 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:21:21,567 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:21:52,691 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:22:23,670 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:22:54,790 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:23:25,548 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:23:56,988 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:24:27,912 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:24:58,436 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:25:29,112 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:25:59,869 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:26:30,776 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:27:01,810 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:27:06,819 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 09:27:27,012 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 09:27:37,077 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:28:08,291 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:28:39,034 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:29:09,943 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:29:40,554 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:30:11,270 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:30:42,286 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:31:12,928 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:31:43,862 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:32:14,382 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:32:45,504 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:33:17,160 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:33:47,876 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:34:18,992 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:34:49,632 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:35:20,644 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:35:51,267 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:36:22,006 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:36:52,710 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:37:23,721 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:37:54,658 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:38:25,148 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:38:55,614 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:39:26,499 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:39:57,153 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:40:27,843 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:40:58,655 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:41:29,140 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:42:00,205 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:42:31,027 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:43:01,853 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:43:32,723 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:44:03,708 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:44:34,402 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:45:05,164 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:45:35,964 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:46:06,656 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:46:37,499 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:47:08,415 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:47:27,426 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 09:47:39,458 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:48:10,704 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:48:41,709 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:49:12,355 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:49:43,064 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:50:13,872 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:50:45,017 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:51:15,483 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:51:46,384 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:52:16,977 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:52:47,722 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:53:18,525 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:53:49,456 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:54:20,287 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:54:51,287 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:55:22,222 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:55:52,834 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:56:23,688 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:56:54,278 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:57:24,799 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:57:55,509 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:58:26,360 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:58:57,368 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:59:28,093 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 09:59:58,813 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:00:29,540 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:01:00,319 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:01:31,072 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:02:01,694 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:02:32,728 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:03:03,647 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:03:35,280 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:04:06,111 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:04:37,052 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:05:07,669 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:05:38,297 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:06:09,085 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:06:39,702 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:07:10,438 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:07:28,425 39777-123145547587584 INFO: Scheduler update_view_times running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:31]
2018-04-25 10:07:41,460 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:08:12,140 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:08:42,885 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:09:13,501 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:09:44,160 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:09:49,167 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 10:10:19,531 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:10:50,153 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:11:21,126 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:11:52,135 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:12:22,978 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:12:53,366 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:13:23,921 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:13:54,941 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:14:25,862 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:14:30,878 39777-123145547587584 ERROR: Failed when updating the huobi prices [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/lgp/Desktop/python-workspace/demo/app/jobs.py", line 50, in huobi_update_prices
    kline_huobi(app)
  File "/Users/lgp/Desktop/python-workspace/demo/app/views/public.py", line 201, in kline_huobi
    datas = byteify(udata)['data']  # 将unicode的key和value转为string
KeyError: 'data'
2018-04-25 10:15:01,064 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
2018-04-25 10:15:32,477 39777-123145547587584 INFO: Scheduler update_prices running: Counter() [in /Users/lgp/Desktop/python-workspace/demo/app/jobs.py:48]
